# Generated by Django 4.1.3 on 2023-04-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlist', '0002_delete_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('privacy', models.CharField(choices=[('PR', 'Private'), ('UL', 'Unlisted'), ('PU', 'Public')], default='PR', max_length=2)),
            ],
        ),
    ]
