# Generated by Django 4.1.3 on 2023-04-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='authorName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='producedAtDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
