# Generated by Django 4.1.3 on 2023-04-18 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_music_authorname_alter_music_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
